apiVersion: v1
kind: Service
metadata:
  labels:
    app: mjpg-streamer
  name: loadbalancer-mjpg-streamer
spec:
  ports:
  - name: mjpg-streamer-port-lb
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mjpg-streamer
  type: LoadBalancer