apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camera
  name: deployment-camera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
      - image: fufuhu/camera:20190720
        name: camera
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: secret-camera
        #command:
        #  - /bin/sh
        #  - -c
        #  - tail -f /dev/null