apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camera
  name: deployment-camera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
      - image: fufuhu/camera:20190722-2
        name: camera
        ports:
        - containerPort: 8000
        env:
        - name: CAMERA_URL_STREAM
          value: http://hoge:hoge@service-mjpg-streamer:8080/?action=stream
        envFrom:
        - secretRef:
            name: secret-camera
        volumeMounts:
        - mountPath: /home/django/app/services/images
          name: volume-image
      - image: fufuhu/s3-syncer:20190721
        name: syncer
        command:
          - ./s3_sync_with_loop.sh
        envFrom:
        - secretRef:
            name: secret-minio
        volumeMounts:
        - mountPath: /images
          name: volume-image
      initContainers:
      - image: fufuhu/s3-syncer:20190721
        name: init-syncer
        command:
          - ./s3_sync.sh
        envFrom:
        - secretRef:
            name: secret-minio
        volumeMounts:
        - mountPath: /images
          name: volume-image
      volumes:
      - name: volume-image
        emptyDir: {}

# /home/django/app/services/images/
# /images